In [2]:
import numpy as np

# 指定文本文件路径
txt_file_path = '/home/Zhouyu/MODEL/task1/code/code/all_chars.txt'

data = np.genfromtxt(txt_file_path, dtype=str)

# 将字符串数据转换为浮点数（示例）
data = data.astype(float)

# 指定保存的 .npy 文件路径
npy_file_path = '/home/Zhouyu/MODEL/task1/code/code/output_file.npy'

# 将数据保存为 .npy 文件
np.save(npy_file_path, data)

ValueError: could not convert string to float: 'p'

In [3]:
import numpy as np

# 指定文本文件路径
txt_file_path = '/home/Zhouyu/MODEL/task1/code/code/all_chars.txt'

# 从文本文件中加载数据
with open(txt_file_path, 'r') as file:
    lines = file.read().splitlines()

# 将每行作为一个元素存储到 numpy 数组中
data = np.array(lines)

# 指定保存的 .npy 文件路径
npy_file_path = '/home/Zhouyu/MODEL/task1/code/code/output_file.npy'

# 将数据保存为 .npy 文件
np.save(npy_file_path, data)

In [6]:
import numpy as np

# 指定.npy文件的路径
file_path = '/home/Zhouyu/MODEL/task1/code/code/output_file.npy'

# 使用NumPy加载.npy文件
data = np.load(file_path)

# 打印数组内容
print(data)

['[p]' '[I]' '[b]' '[\\]' '[r]' '[y]' '[s]' '[F]' '[1]' '[2]' '[V]' '[H]'
 '[:]' '[d]' '[3]' '[G]' '[L]' '[W]' '[T]' '[u]' '[Y]' '[@]' '[R]' '[c]'
 '[0]' '[8]' '[O]' '[]]' '[6]' '[4]' '[i]' '[M]' '[o]' '[f]' '[>]' '[.]'
 '[U]' '[t]' '[[]' '[(]' '[E]' '[g]' '[n]' '[e]' '[K]' '[h]' '[l]' '[a]'
 '[m]' '[=]' '[7]' '[N]' '[-]' '[Z]' '[/]' '[B]' '[+]' '[5]' '[C]' '[)]'
 '[9]' '[D]' '[#]' '[%]' '[X]' '[P]' '[S]' '[A]' '[!]' '[<]']


In [5]:
import numpy as np

# 指定文本文件路径
txt_file_path = '/home/Zhouyu/MODEL/task1/code/code/all_chars.txt'

# 从文本文件中加载数据
with open(txt_file_path, 'r') as file:
    lines = file.read().splitlines()

# 在每个元素周围添加方括号
data = np.array([f"[{elem}]" for elem in lines])

# 指定保存的 .npy 文件路径
npy_file_path = '/home/Zhouyu/MODEL/task1/code/code/output_file.npy'

# 将数据保存为 .npy 文件
np.save(npy_file_path, data)

In [8]:
# 指定文本文件路径
txt_file_path = 'path/to/your/input_file.txt'
txt_file_path = '/home/data/wd/USPTO/uspto_data.txt'
txt_file_path = '/home/data/wd/rxn.txt'

# 指定要读取的行数
num_lines = 5  # 假设读取前5行

# 读取文本文件的前几行
lines = []
with open(txt_file_path, 'r') as file:
    for _ in range(num_lines):
        line = file.readline().strip()
        if line:
            lines.append(line)

# 打印读取的行
for line in lines:
    print(line)

O[CH:8]([CH2:7][NH:6][CH2:5][C:4]1=[CH:3][C:2]([CH3:1])=[CH:22][CH:21]=[CH:20]1)[C:9]1=[CH:10][C:11]([O:17][CH3:18])=[C:12]([O:15][CH3:16])[CH:13]=[CH:14]1>>[CH3:1][C:2]1=[CH:22][CH:21]=[C:20]2[C:4](=[CH:3]1)[CH2:5][NH:6][CH2:7][CH:8]2[C:9]1=[CH:10][C:11]([O:17][CH3:18])=[C:12]([O:15][CH3:16])[CH:13]=[CH:14]1
O=[C:20]([CH3:19])[CH3:22].[NH2:1][C:2]1=[C:3]([C:4](=[O:5])[O:6][CH3:7])[CH:8]=[CH:9][CH:10]=[CH:11]1>>[NH:1]([C:2]1=[C:3]([C:4](=[O:5])[O:6][CH3:7])[CH:8]=[CH:9][CH:10]=[CH:11]1)[CH:20]([CH3:19])[CH3:22]
Cl[C:17](=[O:18])[O:19][CH3:20].[NH2:1][CH2:2][CH2:3][C:4]1=[CH:5][CH:6]=[C:7]([OH:10])[CH:8]=[CH:9]1>>[NH:1]([CH2:2][CH2:3][C:4]1=[CH:5][CH:6]=[C:7]([OH:10])[CH:8]=[CH:9]1)[C:17](=[O:18])[O:19][CH3:20]
C[CH2:13][CH2:12][CH2:11][CH2:10][CH2:9][CH2:8][CH2:7][CH2:6][CH2:5][CH2:4][CH2:3][CH2:2][C:1](=O)O>nan.nan>[CH2:1]=[CH:2][CH2:3][CH2:4][CH2:5][CH2:6][CH2:7][CH2:8][CH2:9][CH2:10][CH2:11][CH2:12][CH3:13]
CC[O:21][C:19](=O)[C:14]1=[C:13]([NH:12][C:10]([NH:9][C:3]2=[C:2]([Cl:1])[CH

In [12]:
# 指定输入文本文件路径
input_file_path = 'path/to/your/input_file.txt'
input_file_path = '/home/data/wd/zinc_data.txt'
input_file_path = '/home/data/wd/USPTO/uspto_data.txt'
input_file_path = '/home/data/wd/rxn.txt'

# 指定输出文本文件路径
output_file_path = '/home/Zhouyu/MODEL/task1/test/asd/c.txt'

# 指定要读取的行数
num_lines = 100  # 假设读取前5行

# 读取前几行并保存至新的文本文件
with open(input_file_path, 'r') as input_file, open(output_file_path, 'w') as output_file:
    for _ in range(num_lines):
        line = input_file.readline()
        if line:
            output_file.write(line)

In [2]:
import torch
from torch.utils.data import DataLoader

def _dataloader_dist(train_set, train_sampler, batch_size, collator):
        torch.multiprocessing.set_start_method('spawn', force=True)
        train_dataloader = DataLoader(
            train_set,
            sampler=train_sampler,
            pin_memory=False,
            num_workers=2,
            persistent_workers=True, 
            drop_last=True,
            batch_size=batch_size,
            collate_fn=collator,
        )
        return train_dataloader

In [3]:
zinc_data_path = '/home/Zhouyu/MODEL/task1/test/asd/a.txt'
uspto_data_path = '/home/Zhouyu/MODEL/task1/test/asd/b.txt'
rxn_data_path = '/home/Zhouyu/MODEL/task1/test/asd/c.txt'

from util.dataloader import ChemData, ChemDataSet, MyTokenizer

all_data = ChemData([zinc_data_path], [uspto_data_path, rxn_data_path])
train_data = ChemDataSet(all_data.train_data)

train_set = train_data

100it [00:00, 400219.85it/s]


processing /home/Zhouyu/MODEL/task1/test/asd/b.txt


100it [00:00, 120.01it/s]


processing /home/Zhouyu/MODEL/task1/test/asd/c.txt


100it [00:00, 207.44it/s]

100 177 177
10 177 177


In [14]:
import torch.distributed as dist

import os
os.environ['RANK'] = '0'
os.environ['WORLD_SIZE'] = '1'
os.environ['MASTER_ADDR'] = '127.0.0.1'
os.environ['MASTER_PORT'] = '29500'


In [15]:
# 初始化进程组
dist.init_process_group(backend='nccl')


In [16]:

train_sampler = torch.utils.data.distributed.DistributedSampler(train_set)

In [17]:

train_dataloader = _dataloader_dist(train_set=train_set, train_sampler=train_sampler, batch_size=64, collator=None)

In [18]:
train_dataloader

In [22]:
train_dataloader.batch_size


64

In [33]:
type(train_set[0])

tuple

In [35]:
import torch

tuple = ({'logp': 4.488800000000003, 'tpsa': 63.08, 'qed': 0.4679355349641039, 'sas': 3.2347381155820223}, [58, 8, 49, 58, 39])

values_list = []
for value in tuple[0].values():
    values_list.append(value)

values_tensor = torch.tensor(values_list)
indices_tensor = torch.tensor(tuple[1])
combined_tensor = torch.cat((values_tensor, indices_tensor))

print(combined_tensor)

tensor([ 4.4888, 63.0800,  0.4679,  3.2347, 58.0000,  8.0000, 49.0000, 58.0000,
        39.0000])


In [36]:
train_set

In [40]:
import torch


new_tuples = []

In [41]:
for original_tuple in train_set:
    values_list = []
    for value in original_tuple[0].values():
        values_list.append(value)
    values_tensor = torch.tensor(values_list)
    indices_tensor = torch.tensor(original_tuple[1])
    new_tuple = (values_tensor, indices_tensor)
    new_tuples.append(new_tuple)

In [42]:
new_tuples

[(tensor([ 4.4888, 63.0800,  0.4679,  3.2347]),
  tensor([58,  8, 49, 58, 39, 54, 58, 49, 51, 54, 26, 58, 58, 58, 51, 58, 23,  9,
          23, 23, 23, 23, 23,  9, 59, 58, 26, 23,  9, 23, 23, 23, 23, 23,  9,  8,
          35, 26, 38, 58, 21, 21, 11, 27, 39, 58, 51, 58, 23,  8, 23, 23, 23, 39,
          58, 46, 59, 23, 23,  8, 59, 58, 26, 54, 51, 49, 58, 54, 58,  8, 49, 58,
          39, 58, 46, 59, 23,  9, 23, 23, 39, 58, 46, 59, 23, 23, 23,  9, 26, 58,
           8, 68])),
 (tensor([ 4.0644, 99.3800,  0.2297,  3.4857]),
  tensor([58,  8, 58, 58, 26, 58, 58,  8, 35, 58, 58, 58, 58, 58, 58, 58, 58, 58,
          58, 58, 58, 58, 58, 58, 58, 58, 58, 26, 38, 58, 21, 11, 27,  8, 26, 38,
          58, 21, 11, 27, 39, 58, 26, 59, 38, 58, 21, 21, 11, 27, 39, 26, 59, 38,
          58, 21, 11, 27, 39, 26, 59, 38, 58, 21, 11, 27,  8, 26, 68])),
 (tensor([ 4.4842, 60.4400,  0.5786,  5.5265]),
  tensor([26, 49, 58,  8, 58, 49, 58, 58,  9, 58, 39, 49, 58,  8, 59, 58, 58, 38,
          58, 21, 11, 27

In [43]:
merged_samples = []
for sample in new_tuples:
    merged_tensor = torch.cat(sample, dim=0)
    merged_samples.append(merged_tensor)

merged_tuple_list = [torch.chunk(sample, chunks=2, dim=0) for sample in merged_samples]

print(merged_tuple_list)

[(tensor([ 4.4888, 63.0800,  0.4679,  3.2347, 58.0000,  8.0000, 49.0000, 58.0000,
        39.0000, 54.0000, 58.0000, 49.0000, 51.0000, 54.0000, 26.0000, 58.0000,
        58.0000, 58.0000, 51.0000, 58.0000, 23.0000,  9.0000, 23.0000, 23.0000,
        23.0000, 23.0000, 23.0000,  9.0000, 59.0000, 58.0000, 26.0000, 23.0000,
         9.0000, 23.0000, 23.0000, 23.0000, 23.0000, 23.0000,  9.0000,  8.0000,
        35.0000, 26.0000, 38.0000, 58.0000, 21.0000, 21.0000, 11.0000, 27.0000]), tensor([39., 58., 51., 58., 23.,  8., 23., 23., 23., 39., 58., 46., 59., 23.,
        23.,  8., 59., 58., 26., 54., 51., 49., 58., 54., 58.,  8., 49., 58.,
        39., 58., 46., 59., 23.,  9., 23., 23., 39., 58., 46., 59., 23., 23.,
        23.,  9., 26., 58.,  8., 68.])), (tensor([ 4.0644, 99.3800,  0.2297,  3.4857, 58.0000,  8.0000, 58.0000, 58.0000,
        26.0000, 58.0000, 58.0000,  8.0000, 35.0000, 58.0000, 58.0000, 58.0000,
        58.0000, 58.0000, 58.0000, 58.0000, 58.0000, 58.0000, 58.0000, 58.0000,


In [61]:
tensor_list = []
for sample in new_tuples:
    new = torch.cat((sample[0], sample[1]), dim=0)
    
    tensor_list.append(new)
    


In [66]:
from torch.nn.utils.rnn import pad_sequence


In [67]:
# 对齐样本到最大序列长度，并使用0进行填充
padded_sequence = pad_sequence(tensor_list, batch_first=True, padding_value=0)

print(padded_sequence)

tensor([[ 4.4888, 63.0800,  0.4679,  ...,  0.0000,  0.0000,  0.0000],
        [ 4.0644, 99.3800,  0.2297,  ...,  0.0000,  0.0000,  0.0000],
        [ 4.4842, 60.4400,  0.5786,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.3762, 36.5000,  0.3932,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.9192, 63.3200,  0.7638,  ...,  0.0000,  0.0000,  0.0000],
        [ 2.9847, 51.6600,  0.7950,  ...,  0.0000,  0.0000,  0.0000]])


In [68]:
padded_sequence.shape

torch.Size([327, 739])

In [69]:
padded_sequence[0]

tensor([ 4.4888, 63.0800,  0.4679,  3.2347, 58.0000,  8.0000, 49.0000, 58.0000,
        39.0000, 54.0000, 58.0000, 49.0000, 51.0000, 54.0000, 26.0000, 58.0000,
        58.0000, 58.0000, 51.0000, 58.0000, 23.0000,  9.0000, 23.0000, 23.0000,
        23.0000, 23.0000, 23.0000,  9.0000, 59.0000, 58.0000, 26.0000, 23.0000,
         9.0000, 23.0000, 23.0000, 23.0000, 23.0000, 23.0000,  9.0000,  8.0000,
        35.0000, 26.0000, 38.0000, 58.0000, 21.0000, 21.0000, 11.0000, 27.0000,
        39.0000, 58.0000, 51.0000, 58.0000, 23.0000,  8.0000, 23.0000, 23.0000,
        23.0000, 39.0000, 58.0000, 46.0000, 59.0000, 23.0000, 23.0000,  8.0000,
        59.0000, 58.0000, 26.0000, 54.0000, 51.0000, 49.0000, 58.0000, 54.0000,
        58.0000,  8.0000, 49.0000, 58.0000, 39.0000, 58.0000, 46.0000, 59.0000,
        23.0000,  9.0000, 23.0000, 23.0000, 39.0000, 58.0000, 46.0000, 59.0000,
        23.0000, 23.0000, 23.0000,  9.0000, 26.0000, 58.0000,  8.0000, 68.0000,
         0.0000,  0.0000,  0.0000,  0.00

In [71]:
# 将填充后的张量保存到文件
torch.save(padded_sequence, 'padded_sequence.pt')
torch.save(tensor_list, 'tensor_list.pt')

In [ ]:

# 加载保存的文件并恢复张量
loaded_sequence = torch.load('padded_sequence.pt')

print(loaded_sequence)

In [ ]:
from config import cfg
from util.model import PropEncoder, ChemGPT
from util.dataloader import ChemData, ChemDataSet
from torch.utils.data import DataLoader

cfg = cfg()
cfg.get_args()
cfgs = cfg.update_train_configs()

zinc_data_path = '/home/data/wd/zinc_data.txt'
uspto_data_path = '/home/data/wd/USPTO/uspto_data.txt'
rxn_data_path = '/home/data/wd/rxn.txt'


zinc_data_path = '/home/Zhouyu/MODEL/task1/test/asd/a.txt'
uspto_data_path = '/home/Zhouyu/MODEL/task1/test/asd/b.txt'
rxn_data_path = '/home/Zhouyu/MODEL/task1/test/asd/c.txt'

all_data = ChemData([zinc_data_path], [uspto_data_path, rxn_data_path])
train_data = ChemDataSet(all_data.train_data)
val_data = ChemDataSet(all_data.val_data)
test_data = ChemDataSet(all_data.test_data)

# padding
data = test_data + train_data + val_data
print(train_data.__getitem__(10))
# max_length = max(len(sequence) for sequence in data)
max_length = max(len(sequence) for sequence in data)
print("最大序列长度:", max_length)

import matplotlib.pyplot as plt

# 假设你有一个名为 data 的序列数据

# 统计序列长度
sequence_lengths = [len(sequence) for sequence in data]

# 绘制直方图
plt.hist(sequence_lengths, bins=20)  # 可根据需要调整 bins 的数量
plt.xlabel('Sequence Length')
plt.ylabel('Count')
plt.title('Sequence Length Distribution')
plt.savefig('/home/Zhouyu/MODEL/task1/test/dist.jpg')

propE = PropEncoder(cfgs)

print(propE.prop_in_dim, propE.embed_dim)

model = ChemGPT(cfgs)